<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // ELEKTRONIK BESAR
            [
                'name' => 'Kulkas LG 2 Pintu 200L Inverter',
                'details' => 'Kulkas bekas terawat baik, berpendingin sempurna, hemat listrik dengan teknologi Inverter. Garansi resmi masih berlaku 6 bulan. Pengiriman gratis untuk wilayah Jabotabek.',
                'price' => 2500000,
                'image_01' => 'fridge1.jpg',
                'condition' => 'good',
                'views' => 234,
                'rating' => 4.6,
            ],
            [
                'name' => 'Mesin Cuci Otomatis Sharp 7kg',
                'details' => 'Mesin cuci bekas normal, pengering lancar, sudah dicek teknisi. Cicilan 0% tersedia. Bisa dikirim dengan armada pribadi.',
                'price' => 1800000,
                'image_01' => 'washer1.jpg',
                'condition' => 'good',
                'views' => 189,
                'rating' => 4.3,
            ],
            [
                'name' => 'AC Panasonic 1.5 PK Inverter',
                'details' => 'AC bekas dirawat baik, dinginnya mantap, remote semua tombol berfungsi normal. Sudah service rutin. Harga negotiable untuk pembelian hari ini.',
                'price' => 2200000,
                'image_01' => 'ac1.jpg',
                'condition' => 'like_new',
                'views' => 312,
                'rating' => 4.7,
            ],
            [
                'name' => 'TV LED Samsung 43 inch Digital',
                'details' => 'TV bekas layar jernih tanpa cacat, warna bagus, remote original. Sedikit garis tipis di bawah bisa diakalin. Bisa cicilan.',
                'price' => 1600000,
                'image_01' => 'tv1.jpg',
                'condition' => 'fair',
                'views' => 156,
                'rating' => 4.2,
            ],
            [
                'name' => 'Kompor Gas 2 Tungku Rinnai',
                'details' => 'Kompor bekas mulus seperti baru, api merata, selang dan regulator sudah diganti baru. Siap pakai langsung.',
                'price' => 450000,
                'image_01' => 'stove1.jpg',
                'condition' => 'like_new',
                'views' => 87,
                'rating' => 4.8,
            ],
            [
                'name' => 'Microwave Panasonic 25L',
                'details' => 'Microwave bekas heating sempurna, panel digital terang, semua mode berfungsi. Jarang pakai, terlihat seperti baru.',
                'price' => 380000,
                'image_01' => 'microwave1.jpg',
                'condition' => 'like_new',
                'views' => 65,
                'rating' => 4.5,
            ],
            [
                'name' => 'Oven Listrik Kue Cosmos 30L',
                'details' => 'Oven bekas terawat, pemanas merata, cocok untuk baking hobi. Gratis wadah pemanggang dan rak ekstra.',
                'price' => 520000,
                'image_01' => 'oven1.jpg',
                'condition' => 'good',
                'views' => 103,
                'rating' => 4.4,
            ],

            // FURNITURE
            [
                'name' => 'Sofa L Minimalis 3 Seater',
                'details' => 'Sofa L bekas terawat, busa empuk, cover bisa dilepas dan dicuci. Panjang 2.5m, lebar 1.8m. Nego untuk pengambilan sendiri.',
                'price' => 3200000,
                'image_01' => 'sofa1.jpg',
                'condition' => 'good',
                'views' => 267,
                'rating' => 4.5,
            ],
            [
                'name' => 'Kasur Spring Bed 160x200 Kotak',
                'details' => 'Kasur bekas bagus banget, busa tebal, spring masih responsive. Sudah dengan bedcover baru. Free ongkir ke Bodetabek.',
                'price' => 2100000,
                'image_01' => 'bed1.jpg',
                'condition' => 'good',
                'views' => 198,
                'rating' => 4.6,
            ],
            [
                'name' => 'Lemari Pakaian Kayu Jati 4 Pintu',
                'details' => 'Lemari bekas kokoh, kayu jati asli, desain klasik elegan. Sedikit warping di pintu bisa disetel. Gratis kursi plastik.',
                'price' => 2800000,
                'image_01' => 'wardrobe1.jpg',
                'condition' => 'fair',
                'views' => 142,
                'rating' => 3.9,
            ],
            [
                'name' => 'Meja Makan Kayu 6 Kursi',
                'details' => 'Meja makan bekas bagus, kayu kuat, kursi lengkap 6 buah empuk. Bisa dilipat kursinya untuk hemat tempat.',
                'price' => 2400000,
                'image_01' => 'diningtable1.jpg',
                'condition' => 'good',
                'views' => 178,
                'rating' => 4.4,
            ],
            [
                'name' => 'Rak Buku 5 Susun Plywood',
                'details' => 'Rak buku bekas kokoh, pas untuk ruang tamu atau kamar. Kapasitas besar untuk banyak koleksi buku dan dekorasi.',
                'price' => 580000,
                'image_01' => 'bookshelf1.jpg',
                'condition' => 'good',
                'views' => 94,
                'rating' => 4.3,
            ],

            // LAPTOP & KOMPUTER
            [
                'name' => 'Laptop HP Pavilion 15 i5-11th Gen',
                'details' => 'Laptop bekas bagus, RAM 8GB, SSD 512GB, display 15.6" FHD. Cocok untuk kerja dan gaming ringan. Garansi internasional aktif.',
                'price' => 5500000,
                'image_01' => 'laptop1.jpg',
                'condition' => 'like_new',
                'views' => 456,
                'rating' => 4.7,
            ],
            [
                'name' => 'Laptop Asus VivoBook 14 FHD',
                'details' => 'Laptop ultrabook bekas mulus, berat ringan ideal untuk mobilitas. Touchpad responsif, layar cerah. Lengkap box dan charger original.',
                'price' => 4200000,
                'image_01' => 'laptop2.jpg',
                'condition' => 'like_new',
                'views' => 323,
                'rating' => 4.8,
            ],
            [
                'name' => 'PC Desktop Core i7 RTX 2060',
                'details' => 'PC gaming bekas powerful, GPU bagus untuk gaming modern. Monitor LG 24" included. Tested semua game mainstream lancar.',
                'price' => 7200000,
                'image_01' => 'pc1.jpg',
                'condition' => 'good',
                'views' => 512,
                'rating' => 4.6,
            ],
            [
                'name' => 'Laptop Bekas Lenovo Thinkpad E14',
                'details' => 'Laptop kerja bekas tangguh, keyboard nyaman, battery masih bagus. Sistem stabil cocok untuk productivity. Ori Windows 10.',
                'price' => 3800000,
                'image_01' => 'laptop3.jpg',
                'condition' => 'good',
                'views' => 267,
                'rating' => 4.5,
            ],

            // SMARTPHONE & TABLET
            [
                'name' => 'iPhone 12 64GB Black',
                'details' => 'iPhone bekas mulus tanpa cacat, baterai sehat 89%, semua fungsi normal. Original charger dan earphone included. Garansi custom 6 bulan.',
                'price' => 6800000,
                'image_01' => 'iphone1.jpg',
                'condition' => 'like_new',
                'views' => 834,
                'rating' => 4.9,
            ],
            [
                'name' => 'Samsung Galaxy A51 128GB',
                'details' => 'Samsung bekas kondisi prima, kamera bagus, baterai awet. Terlihat seperti baru, jarang dipakai. Lengkap box ori dan charger.',
                'price' => 2600000,
                'image_01' => 'phone1.jpg',
                'condition' => 'like_new',
                'views' => 578,
                'rating' => 4.6,
            ],
            [
                'name' => 'iPad 8th Generation 32GB',
                'details' => 'iPad bekas mulus, layar jernih, baterai tahan lama. Cocok untuk media dan entertainment. Sudah with ipad case protective.',
                'price' => 3100000,
                'image_01' => 'ipad1.jpg',
                'condition' => 'good',
                'views' => 456,
                'rating' => 4.5,
            ],
            [
                'name' => 'Xiaomi Redmi Note 10 128GB',
                'details' => 'Xiaomi bekas bagus banget, layar AMOLED jernih, performa lancar. Baterai health 92%, cepat pengisian. Cicilan 0% tersedia.',
                'price' => 1900000,
                'image_01' => 'xiaomi1.jpg',
                'condition' => 'like_new',
                'views' => 334,
                'rating' => 4.4,
            ],

            // CAMERA & FOTOGRAFI
            [
                'name' => 'Kamera DSLR Canon EOS 700D + Lensa',
                'details' => 'Kamera DSLR bekas profesional, lensa kit 18-55mm dan tele 75-300mm included. Shutter count 45k. Tas dan memory card gratis.',
                'price' => 4100000,
                'image_01' => 'camera1.jpg',
                'condition' => 'good',
                'views' => 478,
                'rating' => 4.7,
            ],
            [
                'name' => 'Mirrorless Sony A6000 Body Only',
                'details' => 'Mirrorless bekas ringkas dan mulus, autofocus cepat, battery extended. Cocok untuk travel photography. Tested semua fitur normal.',
                'price' => 3900000,
                'image_01' => 'camera2.jpg',
                'condition' => 'like_new',
                'views' => 389,
                'rating' => 4.8,
            ],
            [
                'name' => 'Kamera Analog Canon AE-1 35mm',
                'details' => 'Kamera analog jadul mulus, mekanik sempurna, lens cerah. Untuk hobi fotografi analog. Include tas kulit dan 2 roll film.',
                'price' => 680000,
                'image_01' => 'camera3.jpg',
                'condition' => 'good',
                'views' => 156,
                'rating' => 4.5,
            ],
            [
                'name' => 'Drone DJI Mavic Air 2 Lengkap',
                'details' => 'Drone bekas terjaga, terbang smooth, kamera 4K jernih. Bonus extra battery dan ND filter set. DJI Care tersedia.',
                'price' => 5200000,
                'image_01' => 'drone1.jpg',
                'condition' => 'good',
                'views' => 567,
                'rating' => 4.7,
            ],

            // AUDIO & MUSIK
            [
                'name' => 'Headphone Sony WH-1000XM4 Wireless',
                'details' => 'Headphone wireless bekas premium, noise cancelling sempurna, suara clear. Baterai tahan 30 jam. Original dengan garansi resmi.',
                'price' => 2900000,
                'image_01' => 'headphone1.jpg',
                'condition' => 'like_new',
                'views' => 612,
                'rating' => 4.9,
            ],
            [
                'name' => 'Speaker Aktif JBL PartyBox 110',
                'details' => 'Speaker aktif bekas powerful, bass menggelegar, cocok untuk acara kecil. Bluetooth dan aux input. Remote control included.',
                'price' => 1400000,
                'image_01' => 'speaker1.jpg',
                'condition' => 'good',
                'views' => 267,
                'rating' => 4.4,
            ],
            [
                'name' => 'Gitar Akustik Yamaha C40',
                'details' => 'Gitar akustik bekas terawat baik, suara resonan bagus, fret masih bagus. Cocok untuk pemula hingga menengah. Include capo dan strap.',
                'price' => 850000,
                'image_01' => 'guitar1.jpg',
                'condition' => 'good',
                'views' => 198,
                'rating' => 4.5,
            ],
            [
                'name' => 'Keyboard Musik Yamaha PSR-E363',
                'details' => 'Keyboard bekas berfungsi normal, 61 keys, sound lengkap, recording fitur ok. Tas tebal dan stand included. Jarang dipakai.',
                'price' => 1200000,
                'image_01' => 'keyboard_music1.jpg',
                'condition' => 'good',
                'views' => 145,
                'rating' => 4.3,
            ],

            // GAMING & HOBI
            [
                'name' => 'Konsol Nintendo Switch OLED',
                'details' => 'Switch OLED bekas mulus, layar cerah, dock normal. Bonus 2 game original dan pro controller. Semua aksesoris lengkap.',
                'price' => 4600000,
                'image_01' => 'switch1.jpg',
                'condition' => 'like_new',
                'views' => 723,
                'rating' => 4.8,
            ],
            [
                'name' => 'Gaming Monitor ASUS 144Hz 27"',
                'details' => 'Monitor gaming bekas refresh rate tinggi, response time cepat, cocok untuk esports. Sedikit dust di panel bisa dibersihkan.',
                'price' => 1800000,
                'image_01' => 'monitor1.jpg',
                'condition' => 'fair',
                'views' => 289,
                'rating' => 4.2,
            ],
            [
                'name' => 'Sepeda MTB Trek Marlin 5',
                'details' => 'Sepeda gunung bekas terawat, ban bagus, komponen responsif. Cocok untuk trail ringan dan XC. Service baru minggu lalu.',
                'price' => 3500000,
                'image_01' => 'bike1.jpg',
                'condition' => 'good',
                'views' => 334,
                'rating' => 4.6,
            ],
            [
                'name' => 'Sepeda Lipat Dahon 20 inch',
                'details' => 'Sepeda lipat bekas praktis, ukuran compact, persneling 7 speed. Cocok untuk commuting dan traveling. Kondisi mesin prima.',
                'price' => 1100000,
                'image_01' => 'bike2.jpg',
                'condition' => 'good',
                'views' => 212,
                'rating' => 4.4,
            ],

            // SPORT & OUTDOOR
            [
                'name' => 'Treadmill Elektrik Osaka',
                'details' => 'Treadmill bekas kuat, incline bisa diatur, motor bertenaga. Cocok untuk home gym. Sedikit suara mesin biasa aja.',
                'price' => 2300000,
                'image_01' => 'treadmill1.jpg',
                'condition' => 'good',
                'views' => 178,
                'rating' => 4.3,
            ],
            [
                'name' => 'Kamera GoPro Hero 9 Black',
                'details' => 'GoPro bekas action camera canggih, waterproof, 4K resolution. Stabilisasi gimbal mantap. Bonus extra battery dan kartu memory.',
                'price' => 2200000,
                'image_01' => 'gopro1.jpg',
                'condition' => 'like_new',
                'views' => 423,
                'rating' => 4.7,
            ],

            // AKSESORIS & GADGET
            [
                'name' => 'Power Bank Anker 65W Fast Charging',
                'details' => 'Power bank bekas kapasitas besar 20000mAh, charge cepat, bisa charge laptop. Multi-port input/output. Kondisi sempurna.',
                'price' => 450000,
                'image_01' => 'powerbank1.jpg',
                'condition' => 'like_new',
                'views' => 334,
                'rating' => 4.6,
            ],
            [
                'name' => 'Smart Watch Apple Watch Series 6',
                'details' => 'Apple Watch bekas mulus, sensor kesehatan akurat, baterai prima. Leather band original included. Garansi custom 3 bulan.',
                'price' => 2100000,
                'image_01' => 'smartwatch1.jpg',
                'condition' => 'like_new',
                'views' => 567,
                'rating' => 4.8,
            ],
            [
                'name' => 'External SSD Samsung T7 1TB',
                'details' => 'SSD eksternal bekas lightning fast, 1TB storage besar, proteksi data ketat. USB C connection, sangat portable dan reliable.',
                'price' => 1200000,
                'image_01' => 'ssd1.jpg',
                'condition' => 'like_new',
                'views' => 289,
                'rating' => 4.7,
            ],
            [
                'name' => 'Router WiFi 6 ASUS AX3000',
                'details' => 'Router mesh bekas performa tinggi, jangkauan luas, WiFi 6 technology. Setup mudah via aplikasi, signal stabil. Garansi resmi masih ada.',
                'price' => 1600000,
                'image_01' => 'router1.jpg',
                'condition' => 'good',
                'views' => 245,
                'rating' => 4.5,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
